### ISSUE TITLE
[BUG]”矩阵“章节小错误（原文无对应错误）

### ISSUE THREAD

**Issue by Traveler0014** [taichi-dev/taichi-docs-zh-cn#101]
在“作为临时的本地变量”标题下：

> ti.Matrix([[x, y, ...][, z, w, ...], ...])

一栏，字母z前逗号位置错误，应改为

> ti.Matrix([[x, y, ...], [z, w, ...], ...])

**Comment by Traveler0014** [comment]
https://taichi.readthedocs.io/zh_CN/latest/matrix.html
忘了贴上对应章节网址了

**Comment by isdanni** [comment]
如果确认没有问题的话，这个issue现在可以关掉了？

**Comment by Traveler0014** [comment]
> 如果确认没有问题的话，这个issue现在可以关掉了？

![image](https://user-images.githubusercontent.com/26181899/90221605-18e12100-de3d-11ea-9cd3-d553e02f5341.png)
目前看到的04c5a12b版本里似乎还存在同一个问题
