### ISSUE TITLE
[翻译完成] dev_install

### ISSUE THREAD

**Issue by rexwangcc** [taichi-dev/taichi-docs-zh-cn#36]

**Comment by yuanming-hu** [comment]
Hi @rexwangcc thanks so much for your help! Just want to let you know that the `Setting up CUDA 10.1 on Ubuntu 18.0` paragraph is being rewritten. Please leave this part untranslated for now, if you haven't started :-)

**Comment by rexwangcc** [comment]
@yuanming-hu Thanks for this timely reminder! I was about to starting the translation 😄 Ok, I will hold off translating that paragraph until I see updates!

**Comment by rexwangcc** [comment]
It seems the doc is updated in commit: https://github.com/taichi-dev/taichi/commit/e6e26533c53f31fc183b5c20dd17f21bdedfc863#diff-97322f732b832df07874b286a638a2a1R55, I will resume the work here.
