### ISSUE TITLE
[翻译需要更新] GUI System

### ISSUE THREAD

**Issue by isdanni** [taichi-dev/taichi-docs-zh-cn#39]

**Comment by archibate** [comment]
Hi! You may already found that `gui.rst` is recently updated in en doc, would you mind to update `gui.po` too? No rush at all! Feel free to take this when you have time!

**Comment by isdanni** [comment]
> Hi! You may already found that `gui.rst` is recently updated in en doc, would you mind to update `gui.po` too? No rush at all! Feel free to take this when you have time!

Yes I will update it soon. Thanks for the heads up! ; - )
