### ISSUE TITLE
[翻译完成] layout

### ISSUE THREAD

**Issue by ArkhamWJZ** [taichi-dev/taichi-docs-zh-cn#61]

**Comment by archibate** [comment]
Just a kind reminder:
data_layout.rst has been renamed to layout.rst with some changes, so you don't have to start-from-zero, you may want to check out data_layout.po (previously by @isdanni) as a base for layout.po to prevent redundant work :)

**Comment by ArkhamWJZ** [comment]
I see. Thanks for your prompt ;)！
